### ISSUE TITLE
Renaming ASR permission

### ISSUE THREAD

**Issue by arichardson** [riscv/riscv-cheri#106]
As has been noted before, ASR grants additional privilege beyond CSR access so the historical "Access System Registers" name may not be the best. Morello uses System which is IMO better, but the abbreviation would conflict with `S` for Store, maybe `Privileged Permission (P)`/`Elevated Permission (E)`/`System Management Permission (SM)`?

**Comment by tariqkurd-repo** [comment]
What should the spec of ASR be? What additional state does it allow access to over CSRs?

**Comment by arichardson** [comment]
I guess you could argue that instructions like `xret` actually read the CSR so ASR isn't needed for the instruction itself but rather the side-effects of that instruction. We can probably ignore this until there is another non-CSR case that needs elevated privilege.

I do wonder if we should require it for ECALL though...

**Comment by sorear** [comment]
#140 and https://lists.riscv.org/g/sig-cheri/message/68 have a fair amount about other uses for ASR and its fundamental nature as the catch-all for resources, whether architectural or software-defined, accessible in a given privilege mode for which a more specific permission is either not needed or intended to be defined at a higher level using sentries.

Personally of the options given I prefer "Elevated (E)" - Privileged invites confusion with privilege levels, and System Management has implications about resource scope which may not be accurate.

**Comment by tariqkurd-repo** [comment]
@arichardson do you want to do something about this one? Or shelve it?

**Comment by andresag01** [comment]
@arichardson : Can we close this ticket?

**Comment by arichardson** [comment]
Let's close this and keep it as is.
