### ISSUE TITLE
Apply taggable PMA to loads as well as stores

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-cheri#121]
We currently have a PMA for stores:

https://github.com/riscv/riscv-cheri/blob/main/src/riscv-integration.adoc#physical-memory-attributes-pma

but nothing for loads. I think that we should reuse the same PMA and do the same for loads as stores i.e. give implementations the choice of 

1. return an access fault
2. load the tag as zero

the point of this is to allow the memory system to avoid the tag lookup which may give performance advantages.

**Comment by tariqkurd-repo** [comment]
tag clearing already specified

**Comment by jrtc27** [comment]
(and required, otherwise you can’t write a tag-preserving memcpy that works on non-taggable memory)
