### ISSUE TITLE
Mode flag value for infinite cap isn't specified

### ISSUE THREAD

**Issue by Timmmm** [riscv/riscv-cheri#13]
`Zcheri_mode` adds a `M` field to the cap. The `NULL and Infinite Capabilities` section specifies that the null cap is all zeros, so presumably that applies to `M` too. It doesn't say what `M` should be for the infinite cap.

I would *guess* it should also be zero since the mode doesn't form part of the null <-> infinite permission spectrum, but it would be good if it said that.

**Comment by arichardson** [comment]
That is a good point, even though the capability respresentation section states that these capabilities have zero in all bits, we might want to clarify that this also includes reserved bits and add a reserved table row.
