### ISSUE TITLE
Tag bits of special capabilities

### ISSUE THREAD

**Issue by jasonyu1996** [riscv/riscv-cheri#138]
In Section 2.3, I believe it is necessary to specify the tag bits of NULL and Infinite capabilities. It seems that NULL's tag bit should be clear according to the definition of `c0` in Section 3.2, and that Infinite's tag bit should be set.

**Comment by arichardson** [comment]
Agreed that this should be added. It's implied by the rest of the spec but we should be explicit here. I'll submit a change for this tomorrow
