### ISSUE TITLE
SC mnemonic does not conflict as stated

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-cheri#14]
The current draft says:

> Renaming SC is not a choice. The store capability instruction must be renamed because it conflicts with store conditional from the RISC-V A extension.

This is not true. Store Capability is always SC.x for some width x.

**Comment by tariqkurd-repo** [comment]
yes - the wording is too strong SC.C is store-conditional of a capability and SC is store capability - so they don't actually conflict.
They are very similar though so if and when we decide to rename the mnemonics we should address this.
