### ISSUE TITLE
CMODESW encoding not clear

### ISSUE THREAD

**Issue by Timmmm** [riscv/riscv-cheri#151]
![image](https://github.com/riscv/riscv-cheri/assets/376842/3b61bcfb-a7a5-4eda-8ea1-819601f54462)

`funct5` is 5 bits bit it only says `000`

**Comment by James-Williams** [comment]
Fixed by https://github.com/riscv/riscv-cheri/pull/152

**Comment by andresag01** [comment]
Closing this because it was resolved in #152
