### ISSUE TITLE
Tag bits not shown in CSR bitfields

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-cheri#16]
For the bitfield diagrams in places like section 3.7.4 only 2*XLENMAX-1 bits are shown, omitting the 2*XLENMAX-th tag bit.

**Comment by tariqkurd-repo** [comment]
@andresag01

**Comment by andresag01** [comment]
@jrtc27 : Thank you for the feedback. These were left out because the tag bit is out-of-band. We can consider drawing the tag bit if it makes it clearer. Is your opinion that we should do this for every extended CSR that has a tag bit?
