### ISSUE TITLE
cbld description does not match code snippet

### ISSUE THREAD

**Issue by tomaird** [riscv/riscv-cheri#186]
The description for `cbld` doesn’t match the code snippet.

The description says “copy `cs2` to `cd` and set the tag to 1 if `cs1.tag` is set” but it makes no mention of **clearing** the tag if `cs1.tag` is **not** set.

![image](https://github.com/riscv/riscv-cheri/assets/24192817/6fcbcab7-f796-4202-882b-04943b8d3921)

The code snippet says that you clear the tag of `cd` if `cs1.tag` is not set. 

![image](https://github.com/riscv/riscv-cheri/assets/24192817/7c3d1fd6-0a81-4eb6-ac3c-7f14d93a33ce)

**Comment by PRugg-Cap** [comment]
Hmm, just spotted this: it mostly doesn't matter, but it can help to leave the tag set when you want to try to buildcap with a chain of possible authorising caps, so we may want the "leave the tag set" behaviour. @jrtc27 has done some work on this and may have thoughts?

**Comment by arichardson** [comment]
> Hmm, just spotted this: it mostly doesn't matter, but it can help to leave the tag set when you want to try to buildcap with a chain of possible authorising caps, so we may want the "leave the tag set" behaviour. @jrtc27 has done some work on this and may have thoughts?

Are you suggesting we just treat this as a move when the input.tag == 1 && auth.tag == 1?
