### ISSUE TITLE
Makefile VERSION does not match Git tag

### ISSUE THREAD

**Issue by andresag01** [riscv/riscv-cheri#20]
The Makefile has this version number https://github.com/riscv/riscv-cheri/blob/main/Makefile#L21 which differs with the git tag of the current revision. It would be good to sync these up.

**Comment by arichardson** [comment]
Agreed that this makes a lot of sense. I'm not quite sure what version we should consider the spec to be at, but since the numbers appear to be mostly arbitrary I'm happy to deploy a 0.7.0 release today.

**Comment by arichardson** [comment]
I've deployed a draft 0.7.0 version now.
