### ISSUE TITLE
Consider renaming Legacy mode to Hybrid mode

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-cheri#231]
Legacy mode implies that the existing architecture will become obselete.
Hybrid mode may be more acceptable, as it shows that there are CHERI features without degrading the base architecture.

**Comment by tariqkurd-repo** [comment]
https://github.com/riscv/riscv-cheri/pull/232

we settled on `integer pointer` and `capability pointer` mode as they are the most descriptive.

**Comment by arichardson** [comment]
This was fixed in https://github.com/riscv/riscv-cheri/pull/232.
