### ISSUE TITLE
Permission encoding order mismatch

### ISSUE THREAD

**Issue by Timmmm** [riscv/riscv-cheri#25]
For RV64 the ADP bits are encoded like this:

![image](https://github.com/riscv/riscv-cheri/assets/376842/62073c31-0cb5-4b27-b5e7-b844561744a5)

However `CGetPerms` and `CAndPerms` expect this order:

![image](https://github.com/riscv/riscv-cheri/assets/376842/114b6305-be45-46a7-9f68-35aae5fb00a1)

The table for encoding RV32 permissions uses the same order (reversed):

![image](https://github.com/riscv/riscv-cheri/assets/376842/ca57cdec-a326-463f-b353-7f8331d15540)

It would be much better if these were consistent!

Also did this question get resolved?

![image](https://github.com/riscv/riscv-cheri/assets/376842/6bf620f1-9436-4cb0-adce-0c41977d28f5)

**Comment by andresag01** [comment]
@Timmmm : Thanks for pointing this out; indeed, it needs to be fixed! Would you like to create an MR for this?

The `TODO` has not been resolved.

**Comment by Timmmm** [comment]
@tariqkurd-repo you mean remove the TODO and leave as-is? If new useful combinations are found what's the plan for RV32? Use the reserved pattern?
