### ISSUE TITLE
GCPERM needs updating

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-cheri#259]
GCPERM says 

![image](https://github.com/riscv/riscv-cheri/assets/59061376/00fd5d57-d826-471b-81e8-932b06955e20)

but this was before we added rules for RV64 permissions, so this needs to be updated to include the RV64 reserved cases

**Comment by andresag01** [comment]
Fixed via https://github.com/riscv/riscv-cheri/pull/261
