### ISSUE TITLE
ddc tag value unclear on debug mode entry

### ISSUE THREAD

**Issue by tomaird** [riscv/riscv-cheri#263]
The spec says:

> Upon entry to debug mode, ddc is saved in dddc. ddc's metadata is set to the Infinite capability’s metadata and ddc's address remains unchanged.

Elsewhere in the spec, the tag bit is treated as a separate entity to the "metadata", so the above quote suggests that if `ddc` had its tag bit cleared before debug entry, that it would stay cleared after debug mode entry, even though the metadata is updated to the infinite cap.

Is this the intention? Or should it also have its tag set on debug mode entry when it gets the infinite cap metadata?

**Comment by PRugg-Cap** [comment]
Agree this should be clarified: I don't think there's any point to changing its metadata if you don't also set the tag. The point is to make debug memory operations be easy to run without having to do a dance to find a capability (which you always can do anyway since `dinfc` exists).

**Comment by andresag01** [comment]
Fixed via #267
