### ISSUE TITLE
Proposed utidc index clashes with cycleh register

### ISSUE THREAD

**Issue by PRugg-Cap** [riscv/riscv-cheri#272]
We propose to use 0xC80 for `utidc`:

https://github.com/riscv/riscv-cheri/blob/f76f4a4f19297b4abc58bfaa62a087ab12542c13/src/tid-ext.adoc?plain=1#L28

However, it's already used by RISC-V priv for `cycleh`:

https://github.com/riscv/riscv-isa-manual/blob/6ee57d8997021aaa8025e208164763fe12e03c19/src/priv-csrs.adoc?plain=1#L165

**Comment by tariqkurd-repo** [comment]
ahh that's because I didn't check it against csrs32.csv in riscv-opcodes
I'll move it

**Comment by tariqkurd-repo** [comment]
also updated in riscv-opcodes: https://github.com/riscv/riscv-opcodes/pull/237

**Comment by tariqkurd-repo** [comment]
Fixed by https://github.com/riscv/riscv-cheri/pull/275
