### ISSUE TITLE
Document conflicts over floating point encodings

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-cheri#29]
C.FSD/C.FSDSP/C.FLD/C.FLDSP are part of Zcd, not Zca, and they conflict with the encoding chosen for C.SC on RV64, so (Zcheri_purecap & Zcd & RV64) is an illegal combination.  Zcmp and Zcmt use the same opcode and also cannot coexist with Zcheri_purecap & RV64.

C.FSW/C.FSWSP/C.FLW/C.FLWSP are part of Zcf, not Zca.

**Comment by tariqkurd-repo** [comment]
Hi @sorear thanks for this - can you check the PR please

**Comment by tariqkurd-repo** [comment]
PR merged
