### ISSUE TITLE
Compressed address CSRs DDC and DDDC should not be referred to as exectuable vectors

### ISSUE THREAD

**Issue by jamie-melling** [riscv/riscv-cheri#297]
Current spec

> Some CSRs store executable vectors as shown in Table 43.

Should be along the lines of: 

> Some CSRs store executable vectors or are data pointers shown in Table 43.

**Comment by tariqkurd-repo** [comment]
https://github.com/riscv/riscv-cheri/pull/299

**Comment by andresag01** [comment]
#299 is already merged, so this ticket can now be closed.
