### ISSUE TITLE
Authorising capability for PREFETCH.I in integer mode

### ISSUE THREAD

**Issue by andresag01** [riscv/riscv-cheri#318]
The spec says that the authorising capability for a PREFETCH.I is:
* The cs1 register in capability pointer mode
* ddc in integer pointer mode

However, ddc is a data capability, so it would make more sense to have pcc (that always has X-permission) authorising the PREFETCH.I in integer pointer mode.

**Comment by andresag01** [comment]
@arichardson @jrtc27 : Do you have a view on this?

**Comment by PRugg-Cap** [comment]
PCC sounds right to me.

**Comment by arichardson** [comment]
I also think PCC makes more sense here.

**Comment by andresag01** [comment]
Ok, thanks for your comments! I will make a PR to address this.
