### ISSUE TITLE
Should the Zstid CSRs be guarded by CRE

### ISSUE THREAD

**Issue by tomaird** [riscv/riscv-cheri#333]
The description for `CRE` says:

> Executing CSR instructions accessing any CSR added by Zcherihybrid (see Table 25) causes an illegal instruction exception

But this doesn't include the CSRs added by Zstid. Should they be included as well?

From @PRugg-Cap :

> We need to make sure sneaky user-mode software can't stash values that are hidden from legacy OSs. That means either TID needs to be guarded on CRE, or more likely (but more annoyingly) we need to have _another_ enable bit for the TIDs.

**Comment by tariqkurd-repo** [comment]
they definitely need an enable bit - so sharing CRE seems most sensible.
opinions?

**Comment by jrtc27** [comment]
If it’s a separate extension it needs its own enable. Even if it’s dependent on CHERI you could write software for CHERI without xtid, which will then be broken if you add xtid without its own enable.

**Comment by PRugg-Cap** [comment]
I was worried you might say that...

**Comment by arichardson** [comment]
I also think there this should not be gated by CRE, but instead using a state-enable bit. The capability extended versions should definitely be guarded by CRE though.

**Comment by tariqkurd-repo** [comment]
yeah - a state enable seems likely to be required
