### ISSUE TITLE
add cheri "quick start" guide

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-cheri#339]
it would be good to have a quick intro of CHERI including the new state, how it behaves, tagged memory overview etc. so that the reader can get the idea behind CHERI in a few minutes.

**Comment by arichardson** [comment]
I agree this would be helpful to have. Are you proposing this to be an introduction section or a separate document?

**Comment by tariqkurd-repo** [comment]
I think a 1 to 2 page intro at the start of the document will do it - to set the scene
