### ISSUE TITLE
Should DPCC follow the same rules as MEPCC?

### ISSUE THREAD

**Issue by tomaird** [riscv/riscv-cheri#343]
The spec describes how `mepcc[0]` (and sometimes `mepcc[1]`) are implicitly zeroed, and that its tag should be cleared if the legalised address is outside the representable range. The description for `sepcc` says it is handled in the same way.

However there is no similar description for `dpcc`. The RISC-V Debug spec says about `dpc`:

> The writability of dpc follows the same rules as mepc as defined in the Privileged Spec. In particular, dpc must be able to hold all valid virtual addresses and the writability of the low bits depends on IALIGN.

So I think it's reasonable to assume that `dpcc` follows the same legalisation and tag clearing rules as `mepcc`, but should this be explicitly called out in this CHERI spec? Just something like:  "`dpcc` follows the same legalisation rules as `mepcc`"

**Comment by andresag01** [comment]
I think you are right. Would be good to clarify this in the spec.
