### ISSUE TITLE
Allow reserved capability bits not to be stored in the register file

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-cheri#353]
I strongly recommend allowing the reserved bits of capabilities not to be stored.

The current specification has 25 reserved bits (26 if a purecap machine).

For an in-order machine then having an extra XLEN+1 bits is a clear cost, but not crazy.

For a large out-of-order machine with possibly hundreds of physical registers then the additional 25 bits is really expensive, and definitely makes a noticeable difference to core area. For example 192 registers x 25-bits = 4800 useless registers.

People complain about the cost of CHERI being too high - we can't do anything about shrinking the capabilities in memory - but we _can_ shrink the registers.

I propose that we allow an implementation not to store the reserved bits in the register file and any non-stored bits will always read as zero

**Comment by jrtc27** [comment]
You need to be able to preserve them for when the tag is 0, otherwise you will break memcpy, and architecturally it's impossible for them to be set when the tag is 1.

**Comment by davidchisnall** [comment]
You could build an architecture that uses different rename registers for tagged and untagged values, but don’t, it will cause you *far* more problems than it will solve.

There are some ways of alleviating these costs in high-end microarchitecture, but they don’t require this from the artchitecture.
