### ISSUE TITLE
Checks on DPCC when entering debug mode

### ISSUE THREAD

**Issue by tomaird** [riscv/riscv-cheri#356]
The CHERI spec says:

> `dpcc` (and consequently `dpc`) are updated with the capability in `pcc` whose address field is set to the address of the next instruction to be executed as described in (RISC-V, 2022) upon debug mode entry.

The RISC-V debug spec says:

> Upon entry to debug mode, `dpc` is updated with the virtual address of the next instruction to be executed

This seems to imply that this "next address" capability is installed directly into PCC, without any checks or legalisation. If this installs an "invalid" capability into PCC, is it expected that any exception will be raised when returning to that PCC (e.g. with `DRET`) or should there be any checking, legalisation or tag-clearing happening at the point that is installed into PCC on debug mode entry?

**Comment by tariqkurd-repo** [comment]
the instruction must be in PCC bounds to be able to be executed at all, which guarantees that the next PC is representable, which is the same as for the link register from JALR - so no further check is required.
