### ISSUE TITLE
Corner cases for SCMODE

### ISSUE THREAD

**Issue by andresag01** [riscv/riscv-cheri#384]
SCMODE currently does not change the capability if mode cannot be set because the permissions are invalid or x is not granted. Should this behavior change to, for example, clear the tag of the capability?

This ticket was created after feedback in https://github.com/riscv/riscv-cheri/pull/382

**Comment by tariqkurd-repo** [comment]
unless there's a very compelling reason to change it I suggest to stabilise the spec as it is

**Comment by andresag01** [comment]
@tariqkurd-repo : Agreed. I do not have a compelling reason, so I will close this ticket. Please feel free to re-open if this changes.
