### ISSUE TITLE
Specialized getter-with-offset instruction for Zstid?

### ISSUE THREAD

**Issue by nwf** [riscv/riscv-cheri#393]
CHERIoT has pondered, for a hypothetical v2 ISA, making our (per-compartment) globals pointer `cgp` more architectural instead of conventional: specifically, making it a freely readable, ASR-gated writable control register.[^cheriot-issue]  The Zstid proposal is quite similar, though with different intended use case.[^0]

Because global sections can be quite sizable (and because CHERIoT-RTOS does not use a GOT/captable indirection), our existing ISA already went some small step in the direction of privileging `cgp` in the ISA, defining an `AUICGP` instruction.  This writes to a register the result of offsetting the `c3` general purpose register by an AUIPC-like large immediate.[^1]

Perhaps the structures to be hung off the `*tid` CSRs might be similarly large or accessed on hot fast paths.[^2]  The full AUIPC immediate seems likely to be too much of an encoding space ask, but might it be worth considering a specialized "`csrr rd, xtid` with immediate offset" instruction for the Zstid proposal?[^3]

[^cheriot-issue]: https://github.com/CHERIoT-Platform/cheriot-sail/issues/43

[^0]: CHERIoT-RTOS does not have much use for TLS proper, and wants "compartment-invocation local storage" instead; the _really_ curious reader is welcome to see how we currently do that, and what we currently do with it, in the recently added https://github.com/CHERIoT-Platform/cheriot-rtos/pull/297.

[^1]: The sail definition is https://github.com/CHERIoT-Platform/cheriot-sail/blob/43dead94f190f87b1bb18a7fe46add98ec97803c/src/cheri_insts.sail#L77-L88

[^2]: For example, things like `snmalloc`'s per-thread allocators have very short fast paths of small-tens of retired instructions; even one more instruction in TLS lookup could be significant.

[^3]: Though note that if this this instruction shifts its immediate, it may also need to be sensitive to capability representation issues, as with the issue of Zcheripurecap's AUIPC vs CHERIoT's AUIPCC.

**Comment by jrtc27** [comment]
No. But this is precisely the kind of thing that can be added with another extension, likely custom.
