### ISSUE TITLE
Floating point loads inconsistent mnemonic

### ISSUE THREAD

**Issue by ricki-code** [riscv/riscv-cheri#395]
Found in `src/insns/load_32bit_fp.adoc`

Should these both be `frd` or `rd` for consistency?

![image](https://github.com/user-attachments/assets/b774b3e9-c3d6-44da-9d52-e549a80b3875)

**Comment by tomaird** [comment]
There's a few other places too, e.g. `c.fld` uses `frd` but `c.flw` uses `rd`:

![image](https://github.com/user-attachments/assets/49b429ad-435f-4cce-b78d-d7578a1541a2)

![image](https://github.com/user-attachments/assets/a3762808-9339-4614-88cd-8ee2da494376)
