### ISSUE TITLE
dfinc updating not very clear

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-cheri#416]
dinfc is written to to control the cheri mode to enter when entering debug mode, and also reports the current cheri mode when in debug mode.

this table needs updating:

![image](https://github.com/user-attachments/assets/5efe12e9-1bcd-4f20-85b1-1285bba0005e)

but also, what do we do about writing caps which don't have X permission, or, for RV32 have invalid permission bits to dfinc.
or are untagged? what should the rules be?

One option is to ignore all writes and only allow MODESW.* to write to it.
This seems the simplest approach.

This is the part which needs clarification:

<img width="638" alt="image" src="https://github.com/user-attachments/assets/f5a00550-a02f-46ab-89a5-ea55321b861e">

**Comment by tariqkurd-repo** [comment]
PR merged

**Comment by arichardson** [comment]
If you include `Fixes: #N` or `Closes: #N` in the commit message when merging, it will autoclose the linked issue.
