### ISSUE TITLE
XLEN-bit results of CSR instructions must be sign extended to XLENMAX

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-cheri#42]
The current description in 6.3.4 says that they are zero extended, at variance with the base ISA.  This applies to both Zcheri_legacy as specified and to the simplified version.

**Comment by jrtc27** [comment]
Probably it should be dropped entirely and just say the extension to XLENMAX follows the base specification

**Comment by andresag01** [comment]
The PR has been merged, so closing this ticket.

**Comment by arichardson** [comment]
> The PR has been merged, so closing this ticket.

If you add `fixes https://github.com/riscv/riscv-cheri/issues/42` (or closes) to the commit message, GitHub will do this automatically.
