### ISSUE TITLE
EL permission rules clarification

### ISSUE THREAD

**Issue by tomaird** [riscv/riscv-cheri#432]
The summary table describes that `CL` and `EL` are only cleared if `CL=0`  on the auth cap (amongst other conditions):

![image](https://github.com/user-attachments/assets/fea583c6-a134-4e26-ba1c-d5aaf9908c80)

But all the descriptions of `EL` don't mention that `CL` must be zero on the auth cap, but do mention all the other conditions. e.g. in `LC`:

![image](https://github.com/user-attachments/assets/dd6bf43a-6753-4855-a8d0-06546036d76c)

I'm assuming the table is correct and `auth_cap.CL=0` is required to clear `CL` and `EL` in the data cap, but it's a bit confusing to leave this out of these text descriptions.

Note, this is not a problem for the SL-perm rules which describe the conditions in full.

**Comment by jamie-melling** [comment]
To me, it seems like changing the `CL` is more like a demotion than removing a permission.  If your auth cap is Global, then you can load Local or Global capabilities, but if your capability is Local, then can only load Local capabilities using it - hence setting `CL=0` when `auth_cap.CL ==0`. 
"restricting capability level to the level of the authorizing capability" is more future proof wording if the capability levels were ever increased.
