### ISSUE TITLE
Should CSR invalid address handling also apply to HW updates of CSRs?

### ISSUE THREAD

**Issue by tomaird** [riscv/riscv-cheri#455]
Section 4.13.1 describes how to handle invalid addresses written to CLEN CSRs by CSR instructions (such as CSRRW). That is, the tag should be cleared if the written capability has a invalid address and non-infinite bounds.

![image](https://github.com/user-attachments/assets/06129875-aab9-4306-8bba-c3dcebaf1f1a)

However it doesn't specify if this should also be done for HW updates of CLEN CSRs.

e.g. if PCC holds an invalid address, with tag set and non-infinite bounds, a CHERI instruction invalid address fault will be taken, and PCC will be written to `mepcc`. Should the tag be cleared on this write to `mepcc`?

**Comment by tariqkurd-repo** [comment]
yeah - it should also include hardware updates
