### ISSUE TITLE
LC with rd=0

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-cheri#52]
This is a constraint in the encoding pages, but it's inconsistent with the handling of loads in the base ISA.

**Comment by andresag01** [comment]
@tariqkurd-repo: Could you take a look at this?

**Comment by tariqkurd-repo** [comment]
Yes - thanks for spotting this - it's leftover from when the encoding for CLC conflicted with CBO.* and so a target of c0 meant CBO instead. This is clearly a mistake now.
