### ISSUE TITLE
Build HTML and publish to Github pages

### ISSUE THREAD

**Issue by Timmmm** [riscv/riscv-cheri#8]
It would be nice to extend the Makefile to support building the spec as HTML and publish the result via Github Pages.

**Comment by tariqkurd-repo** [comment]
feel free!

**Comment by arichardson** [comment]
This would be really nice to have! I'm not entierly sure what else needs to be done besides archiving the HTML, but I can see https://github.com/peaceiris/actions-gh-pages which should fix the deployment problem.

**Comment by Timmmm** [comment]
Ok I got this to work on my fork. For some reason it deployed here: https://blog.timhutt.co.uk/riscv-cheri/

Hopefully it will deploy somewhere more sensible in this repo! I'll send a PR.

**Comment by arichardson** [comment]
Seems to be deployed at https://riscv.github.io/riscv-cheri/ now :)
