### ISSUE TITLE
Disabling zcheri_legacy features is ambiguous

### ISSUE THREAD

**Issue by veselypeta** [riscv/riscv-cheri#91]
Currently the document in section 6.6 states "Zcheri_legacy includes functions to disable most CHERI features.". However the only feature that can be "disabled" is the effective XLEN. We should reword this sentence as it makes it seem like more features of CHERI can be disabled under zcheri_legacy.

**Comment by sorear** [comment]
Will be addressed or obsoleted by #81 .

**Comment by tariqkurd-repo** [comment]
Zcheri_legacy still has the concept of "adding" new instructions, which will be removed once the duplicate mnemonic renaming is complete

**Comment by andresag01** [comment]
#81 was merged recently, so this ticket can now be closed.
